
export const timezones = [
  "(UTC-12) International Date Line West",
  "(UTC-11) Coordinated Universal Time-11",
  "(UTC-10) Hawaii",
  "(UTC-9) Alaska",
  "(UTC-8) Pacific Time (US & Canada)",
  "(UTC-7) Mountain Time (US & Canada)",
  "(UTC-6) Central Time (US & Canada)",
  "(UTC-5) Eastern Time (US & Canada)",
  "(UTC-4) Atlantic Time (Canada)",
  "(UTC-3) Buenos Aires, Greenland",
  "(UTC-2) Mid-Atlantic",
  "(UTC-1) Azores",
  "(UTC+0) London, Dublin, Lisbon",
  "(UTC+1) Amsterdam, Berlin, Rome",
  "(UTC+2) Athens, Cairo, Helsinki",
  "(UTC+3) Moscow, Baghdad, Nairobi",
  "(UTC+4) Abu Dhabi, Baku",
  "(UTC+5) Islamabad, Karachi, Tashkent",
  "(UTC+6) Almaty, Dhaka",
  "(UTC+7) Bangkok, Hanoi, Jakarta",
  "(UTC+8) Beijing, Hong Kong, Singapore",
  "(UTC+9) Tokyo, Seoul",
  "(UTC+10) Sydney, Guam",
  "(UTC+11) Magadan, Solomon Islands",
  "(UTC+12) Auckland, Fiji",
  "(UTC+13) Nuku'alofa"
];
